name: Fresh View Partners
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74011
title: Fresh View Partners
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#751f5e'
    - '#2a441d'
    - '#818181'
    - '#c1c1c3'
  brandStrength: 0.18097068439237773
  lightness: 0.9155253909993917
  saturation: 0.20278821606189013
  rhythmicContrast: 0.5454442950431257
purpose: []
